export {
  createRemoteCoachAgentDispatchEnvelope,
  parseRemoteCoachAgentDispatchEnvelope,
  parseRemoteCoachAgentDispatchResponse,
  serializeRemoteCoachAgentDispatchEnvelope,
  RemoteCoachAgentDispatchEnvelopeSchema,
} from "./remote-dispatch";
export { checkpointThreadIdForSession } from "./identity";
export {
  COACH_AGENT_EVENT_VERSION,
  COACH_AGENT_GRAPH_VERSION,
  COACH_AGENT_RECOVERY_VERSION,
  COACH_AGENT_SESSION_VERSION,
  COACH_AGENT_STATE_VERSION,
  AgentToolRequestSchema,
  AgentToolResultSchema,
  CoachAgentEventSchema,
  CoachAgentIdentitySchema,
  CoachAgentResultSchema,
  SubmitReflectionEventSchema,
  SubmitDisagreementEventSchema,
  ObservePresentedCueEventSchema,
  StartManualCueVisitEventSchema,
  TeachingToolNameSchema,
  TeachingCapabilitySchema,
} from "./types";
export type {
  AgentToolRequest,
  AgentToolResult,
  CoachAgentEvent,
  CoachAgentIdentity,
  CoachAgentResult,
  SubmitReflectionEvent,
  SubmitDisagreementEvent,
  ObservePresentedCueEvent,
  StartManualCueVisitEvent,
  TeachingToolName,
  TeachingCapability,
  SessionSummaryInput,
} from "./types";
export {
  UserReflectionSchema,
  UserClaimSchema,
  DecisionResourcesSchema,
  TeachingDiagnosisInputSchema,
  TeachingDiagnosisOutputSchema,
  LearningThreadSchema,
  CueCaseSchema,
  DiagnosticResultSchema,
  VerdictSchema,
  TransferRuleSchema,
  HingeSchema,
  diagnoseTeachingCue,
  reviseTeachingDiagnosis,
  parseUserReflection,
  buildUserClaims,
  selectHingeCondition,
  buildDiagnosticCapabilities,
  executeDiagnostic,
  synthesizeCoachVerdict,
  createTransferRule,
  updateLearningThread,
} from "./teaching-diagnosis";
export type {
  TeachingDiagnosisInput,
  TeachingDiagnosisOutput,
  UserReflection,
  UserClaim,
  DecisionResources,
  CueCase,
  LearningThread,
  HingeCondition,
  DiagnosticCapability,
  DiagnosticResult,
  CoachVerdict,
  TransferRule,
} from "@cs-coach/contracts";
// This builder is schema-only and does not pull LangGraph into the client
// entry; the Host needs it to bind capabilities without importing the root
// runtime package.
export { buildTeachingCapabilities } from "./capability-builder";
export {
  assertValidSessionWrapUpBundle,
  buildSessionWrapUpRequest,
  deterministicSessionWrapUpResult,
  SessionWrapUpBundleSchema,
  SessionWrapUpRequestSchema,
  SessionWrapUpResultSchema,
} from "./session-wrap-up";
export {
  SESSION_RECOVERY_RECORD_VERSION,
  FrozenReviewPlanSchema,
  HostToolLedgerSummarySchema,
  PreparedNarrationArtifactSchema,
  RecoveryBoundarySchema,
  RecoveryStableBoundaryUpdateSchema,
  ReplayAvailabilitySchema,
  SessionRecoveryEventSchema,
  SessionRecoveryRecordSchema,
  SessionRecoveryResultSchema,
  ReconnectToolDispositionSchema,
  reconnectDispositionFromLedger,
} from "./recovery-contract";
export type {
  SessionWrapUpBuildInput,
  SessionWrapUpRequest,
  SessionWrapUpResult,
  PresentableSessionWrapUpCue,
} from "./session-wrap-up";
export type {
  FrozenReviewPlan,
  HostToolLedgerSummary,
  RecoveryBoundaryProjection,
  RecoveryIdentity,
  RecoveryPostedToolLedgerEntry,
  RecoveryReplayAvailability,
  SessionRecoveryEvent,
  SessionRecoveryRecord,
  SessionRecoveryResult,
  SessionRecoveryRuntime,
  ReconnectToolDisposition,
  PreparedNarrationArtifact,
} from "./recovery-contract";
